AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  EC2ImageId:
    Description: The EC2 Machine Image ID
    Type: String
    Default: ami-0729e439b6769d6ab
  EC2InstanceType:
    Description: The Instance type of the EC2 instances to be created
    Type: String
    Default: t2.medium
  EBSVolumeSize:
    Description: The EBS Volume size of the EC2 instances to be created
    Type: String
    Default: "10"
  ScalingGroupMinSize:
    Description: The Minimum number of EC2 instances to be deployed by the auto scaling group
    Type: String
    Default: "4"
  ScalingGroupMaxSize:
    Description: The Maxinum number of EC2 instances to be deployed by the auto scaling group
    Type: String
    Default: "8"

Resources:
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our load balancer
      VpcId: !ImportValue
        "Fn::Sub": "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our host and SSH from local only
      VpcId: !ImportValue
        "Fn::Sub": "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  WebApplicationLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref EC2ImageId
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref EBSVolumeSize
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          echo "Udagram Application is Up and Running!" > index.html
  WebApplicationScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue
          "Fn::Sub": "${EnvironmentName}-PRI-NETS"
      LaunchConfigurationName: !Ref WebApplicationLaunchConfiguration
      MinSize: !Ref ScalingGroupMinSize
      MaxSize: !Ref ScalingGroupMaxSize
      TargetGroupARNs:
        - !Ref WebApplicationTargetGroup
  WebApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !ImportValue
          "Fn::Sub": "${EnvironmentName}-PUB1-SN"
        - !ImportValue
          "Fn::Sub": "${EnvironmentName}-PUB2-SN"
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebApplicationTargetGroup
      LoadBalancerArn: !Ref WebApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  LoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref WebApplicationTargetGroup
      Conditions:
        - Field: path-pattern
          Values: [/]
      ListenerArn: !Ref Listener
      Priority: 1
  WebApplicationTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue
        "Fn::Sub": "${EnvironmentName}-VPCID"

Outputs:
  LoadBalancerUrl:
    Description: The load balancer url to publicly access the web application
    Value: !Join ["", ["http://", !GetAtt WebApplicationLoadBalancer.DNSName]]
    Export:
      Name: !Sub ${EnvironmentName}-LB-DNS
